baseurl = "https://i.vince.pub"
languageCode = "zh-CN"
theme = "hugo-theme-stack"
paginate = 5
title = "Vince"
disqusShortname = "hugo-theme-stack"            # Change it to your Disqus shortname before using
DefaultContentLanguage = "en"                   # Theme i18n support

[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"
    
[params]
    mainSections = ["post"]
    featuredImageField = "image"
    rssFullContent = true
    
    [params.dateFormat]
        published = "Jan 02, 2006"
        lastUpdated = "Jan 02, 2006 15:04 MST"
        
    [params.sidebar]
        emoji = "🍉"
        avatar = "img/i.jpg"
        subtitle = "five 养成计划"
        
    [params.article]
        math = true
        [params.article.license]
            enabled = true 
            default = "Licensed under CC BY-NC-SA 4.0"
            
    [params.comments]
        enabled = true
        provider = "gitalk"         # Available: disqus, utterances    
        [params.comments.utterances]
            repo = ""
            issueTerm = "pathname"
            label = ""             # Optional
            theme = "preferred-color-scheme"
            
    [params.widgets]
        enabled = ['search', 'archives', 'tag-cloud']
        [params.widgets.archives]
            limit = 5
            ### Archives page relative URL
            path = "archives"       
        [params.widgets.tagCloud]
            limit = 10
            
    [params.opengraph]
        [params.opengraph.twitter]
            site = ""
            card = "summary_large_image"
            
    [params.defaultImage]
        [params.defaultImage.opengraph]
            enabled = false
            local = false
            src = ""
            
[menu]
    [[menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
        weight = -100
        pre = "home"
    [[menu.main]]
        identifier = "about-cn"
        name = "About"
        url = "about"
        weight = -90
        pre = "user"
    [[menu.main]]
        identifier = "archives"
        name = "Archives"
        url = "archives"
        weight = -70
        pre = "archives"
    [[menu.main]]
        identifier = "search"
        name = "Search"
        url = "search"
        weight = -60
        pre = "search"
    [[menu.main]]
        identifier = "Legacy"
        name = "Legacy"
        url = "https://old.vince.pub/"
        weight = -5
        pre = "arrow-back"

[related]
    includeNewer = true
    threshold = 60
    toLower = false

    [[related.indices]]
        name = "tags"
        weight = 100

    [[related.indices]]
        name = "categories"
        weight = 200

[markup]
    [markup.highlight]
        noClasses = true

    [markup.goldmark]
      [markup.goldmark.renderer]
         unsafe = true



